/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PainelEquipeRouteImport } from './routes/painel-equipe'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FechamentoRouteImport } from './routes/fechamento'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AnunciosRouteImport } from './routes/anuncios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as ApiPublicWebhookReceiverRouteImport } from './routes/api/public/webhook-receiver'
import { Route as ApiPublicSyncpayWebhookRouteImport } from './routes/api/public/syncpay-webhook'
import { Route as ApiPublicSendDailySummaryRouteImport } from './routes/api/public/send-daily-summary'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelEquipeRoute = PainelEquipeRouteImport.update({
  id: '/painel-equipe',
  path: '/painel-equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FechamentoRoute = FechamentoRouteImport.update({
  id: '/fechamento',
  path: '/fechamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciosRoute = AnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookReceiverRoute =
  ApiPublicWebhookReceiverRouteImport.update({
    id: '/api/public/webhook-receiver',
    path: '/api/public/webhook-receiver',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncpayWebhookRoute = ApiPublicSyncpayWebhookRouteImport.update({
  id: '/api/public/syncpay-webhook',
  path: '/api/public/syncpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendDailySummaryRoute =
  ApiPublicSendDailySummaryRouteImport.update({
    id: '/api/public/send-daily-summary',
    path: '/api/public/send-daily-summary',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fechamento': typeof FechamentoRoute
  '/historico': typeof HistoricoRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/painel-equipe': typeof PainelEquipeRoute
  '/registro': typeof RegistroRoute
  '/relatorios': typeof RelatoriosRoute
  '/painel/': typeof PainelIndexRoute
  '/api/public/send-daily-summary': typeof ApiPublicSendDailySummaryRoute
  '/api/public/syncpay-webhook': typeof ApiPublicSyncpayWebhookRoute
  '/api/public/webhook-receiver': typeof ApiPublicWebhookReceiverRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fechamento': typeof FechamentoRoute
  '/historico': typeof HistoricoRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/painel-equipe': typeof PainelEquipeRoute
  '/registro': typeof RegistroRoute
  '/relatorios': typeof RelatoriosRoute
  '/painel': typeof PainelIndexRoute
  '/api/public/send-daily-summary': typeof ApiPublicSendDailySummaryRoute
  '/api/public/syncpay-webhook': typeof ApiPublicSyncpayWebhookRoute
  '/api/public/webhook-receiver': typeof ApiPublicWebhookReceiverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fechamento': typeof FechamentoRoute
  '/historico': typeof HistoricoRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/painel-equipe': typeof PainelEquipeRoute
  '/registro': typeof RegistroRoute
  '/relatorios': typeof RelatoriosRoute
  '/painel/': typeof PainelIndexRoute
  '/api/public/send-daily-summary': typeof ApiPublicSendDailySummaryRoute
  '/api/public/syncpay-webhook': typeof ApiPublicSyncpayWebhookRoute
  '/api/public/webhook-receiver': typeof ApiPublicWebhookReceiverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anuncios'
    | '/configuracoes'
    | '/fechamento'
    | '/historico'
    | '/integracoes'
    | '/login'
    | '/metas'
    | '/notificacoes'
    | '/painel-equipe'
    | '/registro'
    | '/relatorios'
    | '/painel/'
    | '/api/public/send-daily-summary'
    | '/api/public/syncpay-webhook'
    | '/api/public/webhook-receiver'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncios'
    | '/configuracoes'
    | '/fechamento'
    | '/historico'
    | '/integracoes'
    | '/login'
    | '/metas'
    | '/notificacoes'
    | '/painel-equipe'
    | '/registro'
    | '/relatorios'
    | '/painel'
    | '/api/public/send-daily-summary'
    | '/api/public/syncpay-webhook'
    | '/api/public/webhook-receiver'
  id:
    | '__root__'
    | '/'
    | '/anuncios'
    | '/configuracoes'
    | '/fechamento'
    | '/historico'
    | '/integracoes'
    | '/login'
    | '/metas'
    | '/notificacoes'
    | '/painel-equipe'
    | '/registro'
    | '/relatorios'
    | '/painel/'
    | '/api/public/send-daily-summary'
    | '/api/public/syncpay-webhook'
    | '/api/public/webhook-receiver'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnunciosRoute: typeof AnunciosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FechamentoRoute: typeof FechamentoRoute
  HistoricoRoute: typeof HistoricoRoute
  IntegracoesRoute: typeof IntegracoesRoute
  LoginRoute: typeof LoginRoute
  MetasRoute: typeof MetasRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PainelEquipeRoute: typeof PainelEquipeRoute
  RegistroRoute: typeof RegistroRoute
  RelatoriosRoute: typeof RelatoriosRoute
  PainelIndexRoute: typeof PainelIndexRoute
  ApiPublicSendDailySummaryRoute: typeof ApiPublicSendDailySummaryRoute
  ApiPublicSyncpayWebhookRoute: typeof ApiPublicSyncpayWebhookRoute
  ApiPublicWebhookReceiverRoute: typeof ApiPublicWebhookReceiverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-equipe': {
      id: '/painel-equipe'
      path: '/painel-equipe'
      fullPath: '/painel-equipe'
      preLoaderRoute: typeof PainelEquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fechamento': {
      id: '/fechamento'
      path: '/fechamento'
      fullPath: '/fechamento'
      preLoaderRoute: typeof FechamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncios': {
      id: '/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof AnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook-receiver': {
      id: '/api/public/webhook-receiver'
      path: '/api/public/webhook-receiver'
      fullPath: '/api/public/webhook-receiver'
      preLoaderRoute: typeof ApiPublicWebhookReceiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/syncpay-webhook': {
      id: '/api/public/syncpay-webhook'
      path: '/api/public/syncpay-webhook'
      fullPath: '/api/public/syncpay-webhook'
      preLoaderRoute: typeof ApiPublicSyncpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-daily-summary': {
      id: '/api/public/send-daily-summary'
      path: '/api/public/send-daily-summary'
      fullPath: '/api/public/send-daily-summary'
      preLoaderRoute: typeof ApiPublicSendDailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnunciosRoute: AnunciosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FechamentoRoute: FechamentoRoute,
  HistoricoRoute: HistoricoRoute,
  IntegracoesRoute: IntegracoesRoute,
  LoginRoute: LoginRoute,
  MetasRoute: MetasRoute,
  NotificacoesRoute: NotificacoesRoute,
  PainelEquipeRoute: PainelEquipeRoute,
  RegistroRoute: RegistroRoute,
  RelatoriosRoute: RelatoriosRoute,
  PainelIndexRoute: PainelIndexRoute,
  ApiPublicSendDailySummaryRoute: ApiPublicSendDailySummaryRoute,
  ApiPublicSyncpayWebhookRoute: ApiPublicSyncpayWebhookRoute,
  ApiPublicWebhookReceiverRoute: ApiPublicWebhookReceiverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
